### ISSUE TITLE
IDE data routing to file/ide cannot be turned off entirely

### ISSUE THREAD

**Issue by amharrison** [amharrison/jactr-eclipse#2]
Specifically, one or the other must be enabled. Turning off both will result in an exception. The problem is in the generation of the environment file by the IDE. It assumes that we always listen to at least one or the other.

**Comment by monochromata** [comment]
Could you provide the name of the class that throws the exception, the type of exception, and the name of the class class that generates the environment file? Thanks!

**Comment by amharrison** [comment]
The exception is innocuous, String index exception. Arising from org.jactr.eclipse.runtime.launching.env.EnvironmentConfigurator.setupRuntimeTraces(). This class is responsible for converting run configurations into the environment.xml file that is used to setup the runtime.
However, this is where things get complicated. 
* In debug mode, certain tracers are required (ProceduralModuleTracer), as is the networked sink. 
* we turn off all tracers, regardless of debug mode, if running iterative (as they slow things down), unless they are only going to file.
* otherwise, it should conform to what the run config requests.

The class far predates any of the tracing functionality, and so it was shoe-horned in poorly.

**Comment by amharrison** [comment]
Fixed. Either turning off routing to IDE/File  OR turning off all tracers will now work correctly.
